### ISSUE TITLE
How to install the plugin for phonegap

### ISSUE THREAD

**Issue by Ava-UwU** [artberri/cordova-plugin-play-games-services#14]
Hi. So I'm trying to use your sample to make google play games work in my game but there's a problem with the export in phonegap, I did not understand how to edit the config.xml and what exactly to add, I see the line you mentioned (cordova plugin add cordova-plugin-play-games-services --variable APP_ID=you_app_id_here) but the config.xml file has a different format for plugins.
this is my config.xml I'd really appreciate it if you help me out with this.

<?xml version="1.0" encoding="UTF-8" ?>
<widget id="com.ary.ckiller" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
	<name>CK</name>
	<description>C K</description>
	<author>ary</author>

	<icon src="www/icon-256.png" width="256" height="256" density="xxxhdpi" />
	<icon src="www/icon-128.png" width="128" height="128" density="xhdpi" />

	<preference name="android-targetSdkVersion" value="28" />

	<preference name="orientation" value="landscape" />
	<preference name="fullscreen" value="true" />
	<preference name="DisallowOverscroll" value="true" />
	<preference name="AllowInlineMediaPlayback" value="true" />

	<config-file parent="UIStatusBarHidden" platform="ios" target="*-Info.plist"><true/></config-file>
	<config-file parent="UIViewControllerBasedStatusBarAppearance" platform="ios" target="*-Info.plist"><false/></config-file>

	<preference name="deployment-target" value="10.0" />
	<preference name="android-minSdkVersion" value="21" />
	<access origin="*" />

	<plugin name="cordova-custom-config" />
	<plugin name="cordova-plugin-file" />
	<plugin name="cordova-plugin-inappbrowser" />
	<plugin name="cordova-plugin-statusbar" />
	<plugin name="cordova-plugin-whitelist" />
	<plugin name="cordova-plugin-wkwebview-engine" />

	<engine name="ios" />
	<engine name="android" />
</widget>

**Comment by princesanjivy** [comment]
Just fetch it from the npm repo
`    <plugin name="cordova-plugin-play-games-services" source="npm" >
        <param name="APP_ID" value="YOURAPPID" />
    </plugin>`
http://docs.phonegap.com/phonegap-build/configuring/plugins/ check this page for more reference

But when I build it using PhonegapBuild I get an error 
 package com.google.android.gms.games.request does not exist
